### ISSUE TITLE
[ERROR] [domain.co.uk] 10000, Authentication error

### ISSUE THREAD

**Issue by counterfitninja** [KrykiZZ/CloudFlareDDNS#2]
This script will be really useful, however i get the following error when i run it. 

[ERROR] [domain.co.uk] 10000, Authentication error

**Comment by KrykiZZ** [comment]
Provide a valid api key and zone id in your domain config.

**Comment by counterfitninja** [comment]
Yeah i already have those.

**Comment by KrykiZZ** [comment]
Double check it. All my domains working fine.

**Comment by counterfitninja** [comment]
I was trying to use an API token and not eh global API Keys. Things are now working. 

Good work!
